on:
  pull_request_target:
    types: [ opened, edited ]
    
name: conventional-release-labels
permissions:
  contents: write
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
      
